name: JAVA CI
on: 
 push:
  branches: [ "main"]
jobs:
  build:
   runs-on: ubuntu-24.04
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Set Up java
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: 17
     - name: Compile java code
       run: javac App.java
     - name: Run java code
       run: java App
